### ISSUE TITLE
contatto

### ISSUE THREAD

**Issue by NikartikTheBear** [bitpredator/bitpredator#1]
Ciao, scusa se ti contatto così ma non avevo idea di come fare altrimenti 😅 

Ho notato che hai proposto parecchie modifiche di traduzione in tutte le risorse di esx, non so se ne sei a conoscenza ma esx ha avviato un programma ufficiale per le traduzioni, se fossi interessato ad entrare nel discord, principalmente per potersi coordinare meglio con le cose, contattami pure su ds che ti mando l'invito

https://discord.com/users/401728769297219584

Buona continuazione

**Comment by bitpredator** [comment]
Ciao, @NikartikTheBear, sono presente nel discord ufficiale di ESX Framework, tuttavia utilizzo discord molto raramente.
